"""Generates sql/seed_data.sql from data/*.csv (raw values, no cleaning).
Blank cells become NULL. Run from repo root: python sql/make_seed.py"""
import csv

def lit(v, numeric):
    if v == "":
        return "NULL"
    return v if numeric else "'" + v.replace("'", "''") + "'"

SPEC = {  # table: (csv file, set of numeric columns)
    "customers": ("data/customers.csv", {"city_tier"}),
    "products":  ("data/products.csv",  {"price"}),
    "orders":    ("data/orders.csv",    {"quantity", "discount_pct", "rating", "returned"}),
}
out = ["-- Generated by sql/make_seed.py from data/*.csv. Raw, uncleaned.", "BEGIN;"]
for table, (path, numeric) in SPEC.items():
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            cols = ", ".join(row)
            vals = ", ".join(lit(v.strip(), c in numeric) for c, v in row.items())
            out.append(f"INSERT INTO {table} ({cols}) VALUES ({vals});")
out.append("COMMIT;")
with open("sql/seed_data.sql", "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote sql/seed_data.sql")
